# holds one production rule with a marker. Item sets are just sets of items
class Item:
    def __init__(self, lhs, symbols, marker_index=0):
        self.lhs = lhs
        self.symbols = symbols
        self.marker = 0  # the symbols index right after the marker. So for say a.bc, marker would be 1


"""
I: an item set of the grammar G
X: is a symbol of the grammar: in N or in Σ or is $
returns an item set generated by the items in I progressed past X, which may be the same as I
"""
def go_to(I, X):
    K = set()
    for k in I:
        if k.symbols[k.marker] == X:
            K.add(k)

    for k in K:
        k.marker += 1

    return closure(K)

