# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import GenericRepr, Snapshot


snapshots = Snapshot()

snapshots['test_from_str 1'] = GenericRepr("\nTerminals: \nNon-terminals: S\n\n(1)\t S -> lambda $\nPredict ['$']\nGrammar Start Symbol or Goal: S\n\nFirst sets:\nS : ['$']\nFollow sets:\nS : []\n")

snapshots['test_sampleCFG 1'] = GenericRepr("\nTerminals: i, o, plus, taco, times, x, y, z\nNon-terminals: A, B, C, D, E, F, G, S\n\n(1)\t A -> A times C\nPredict ['x']\n(2)\t A -> x\nPredict ['x']\n(3)\t B -> C plus B\nPredict ['z']\n(4)\t B -> y\nPredict ['y']\n(5)\t C -> z D D\nPredict ['z']\n(6)\t D -> E F G\nPredict ['i', 'o']\n(7)\t E -> F i\nPredict ['i', 'o']\n(8)\t E -> i F\nPredict ['i']\n(9)\t F -> F o\nPredict ['o']\n(10)\t F -> lambda\nPredict ['i', 'o', 'taco']\n(11)\t G -> taco\nPredict ['taco']\n(12)\t S -> A\nPredict ['x']\n(13)\t S -> B\nPredict ['y', 'z']\n(14)\t S -> S $\nPredict ['x', 'y', 'z']\nGrammar Start Symbol or Goal: S\n\nFirst sets:\nA : ['x']\nB : ['y', 'z']\nC : ['z']\nD : ['i', 'o']\nE : ['i', 'o']\nF : ['o']\nG : ['taco']\nS : ['x', 'y', 'z']\nFollow sets:\nA : ['$', 'times']\nB : ['$']\nC : ['$', 'plus', 'times']\nD : ['$', 'i', 'o', 'plus', 'times']\nE : ['o', 'taco']\nF : ['i', 'o', 'taco']\nG : ['$', 'i', 'o', 'plus', 'times']\nS : ['$']\n")

snapshots['test_sampleCFG2 1'] = GenericRepr("\nTerminals: a, b, e, equal, f, g, h, j, k, plus, s, t, times, zero\nNon-terminals: A, E, S, T, VAR\n\n(1)\t A -> T A\nPredict ['e', 'f', 'g', 'h', 'j', 'k']\n(2)\t A -> lambda\nPredict ['$']\n(3)\t E -> VAR\nPredict ['e', 'f', 'g', 'h', 'j', 'k']\n(4)\t E -> a plus b\nPredict ['a']\n(5)\t E -> s times t\nPredict ['s']\n(6)\t E -> zero\nPredict ['zero']\n(7)\t S -> A $\nPredict ['$', 'e', 'f', 'g', 'h', 'j', 'k']\n(8)\t T -> VAR equal E\nPredict ['e', 'f', 'g', 'h', 'j', 'k']\n(9)\t VAR -> e\nPredict ['e']\n(10)\t VAR -> f\nPredict ['f']\n(11)\t VAR -> g\nPredict ['g']\n(12)\t VAR -> h\nPredict ['h']\n(13)\t VAR -> j\nPredict ['j']\n(14)\t VAR -> k\nPredict ['k']\nGrammar Start Symbol or Goal: S\n\nFirst sets:\nA : ['e', 'f', 'g', 'h', 'j', 'k']\nE : ['a', 'e', 'f', 'g', 'h', 'j', 'k', 's', 'zero']\nS : ['$', 'e', 'f', 'g', 'h', 'j', 'k']\nT : ['e', 'f', 'g', 'h', 'j', 'k']\nVAR : []\nFollow sets:\nA : ['$']\nE : ['$', 'e', 'f', 'g', 'h', 'j', 'k']\nS : []\nT : ['$', 'e', 'f', 'g', 'h', 'j', 'k']\nVAR : ['$', 'e', 'equal', 'f', 'g', 'h', 'j', 'k']\n")

snapshots['test_sample 1'] = GenericRepr("\nTerminals: a, b, d, g, h\nNon-terminals: A, B, C, D, S\n\n(1)\t A -> B C\nPredict ['$', 'g', 'h']\n(2)\t A -> d a\nPredict ['d']\n(3)\t B -> g\nPredict ['g']\n(4)\t B -> lambda\nPredict ['$', 'a', 'g', 'h']\n(5)\t C -> h\nPredict ['h']\n(6)\t C -> lambda\nPredict ['$', 'b', 'g', 'h']\n(7)\t D -> A C B\nPredict ['$', 'd', 'g', 'h']\n(8)\t D -> B a\nPredict ['a', 'g']\n(9)\t D -> C b b\nPredict ['b', 'h']\n(10)\t S -> D $\nPredict ['$', 'a', 'b', 'd', 'g', 'h']\nGrammar Start Symbol or Goal: S\n\nFirst sets:\nA : ['d', 'g', 'h']\nB : ['g']\nC : ['h']\nD : ['a', 'b', 'd', 'g', 'h']\nS : ['$', 'a', 'b', 'd', 'g', 'h']\nFollow sets:\nA : ['$', 'g', 'h']\nB : ['$', 'a', 'g', 'h']\nC : ['$', 'b', 'g', 'h']\nD : ['$']\nS : []\n")

snapshots['test_sample2 1'] = GenericRepr("\nTerminals: e, f, z\nNon-terminals: A, B, C, S\n\n(1)\t A -> B A B\nPredict ['e', 'f', 'z']\n(2)\t A -> lambda\nPredict ['e', 'f', 'z']\n(3)\t A -> z z A z z\nPredict ['z']\n(4)\t B -> C A C\nPredict ['e', 'f', 'z']\n(5)\t C -> e A f\nPredict ['e']\n(6)\t C -> lambda\nPredict ['e', 'f', 'z']\n(7)\t S -> z A z $\nPredict ['z']\nGrammar Start Symbol or Goal: S\n\nFirst sets:\nA : ['e', 'z']\nB : ['e', 'z']\nC : ['e']\nS : ['z']\nFollow sets:\nA : ['e', 'f', 'z']\nB : ['e', 'f', 'z']\nC : ['e', 'f', 'z']\nS : []\n")

snapshots['test_predict_set_example 1'] = GenericRepr("\nTerminals: a, b, c, d, q\nNon-terminals: A, B, C, Q, S\n\n(1)\t A -> B Q\nPredict ['$', 'b', 'c', 'q']\n(2)\t A -> a B C d\nPredict ['a']\n(3)\t B -> b B\nPredict ['b']\n(4)\t B -> lambda\nPredict ['$', 'c', 'd', 'q']\n(5)\t C -> c\nPredict ['c']\n(6)\t C -> lambda\nPredict ['$', 'd']\n(7)\t Q -> lambda\nPredict ['$', 'c']\n(8)\t Q -> q\nPredict ['q']\n(9)\t S -> A C $\nPredict ['$', 'a', 'b', 'c', 'q']\nGrammar Start Symbol or Goal: S\n\nFirst sets:\nA : ['a', 'b', 'q']\nB : ['b']\nC : ['c']\nQ : ['q']\nS : ['$', 'a', 'b', 'c', 'q']\nFollow sets:\nA : ['$', 'c']\nB : ['$', 'c', 'd', 'q']\nC : ['$', 'd']\nQ : ['$', 'c']\nS : []\n")

snapshots['test_regex_grammar 1'] = GenericRepr("\nTerminals: (, ), *, +, -, =, a, b, c, d, “|”\nNon-terminals: ALTERNATION, BAR, CHAR, GROUPING, LPAREN, MINUS, PLUS, QUANTIFIER, RANGE, RPAREN, SEQUENCE, STAR, TERMINAL, \ufeffREGEX\n\n(1)\t ALTERNATION -> SEQUENCE\nPredict ['(', '=', 'a', 'b', 'c', 'd']\n(2)\t ALTERNATION -> SEQUENCE BAR ALTERNATION\nPredict ['(', '=', 'a', 'b', 'c', 'd']\n(3)\t BAR -> “|”\nPredict ['“|”']\n(4)\t CHAR -> a\nPredict ['a']\n(5)\t CHAR -> b\nPredict ['b']\n(6)\t CHAR -> c\nPredict ['c']\n(7)\t CHAR -> d\nPredict ['d']\n(8)\t GROUPING -> LPAREN ALTERNATION RPAREN\nPredict ['(']\n(9)\t GROUPING -> TERMINAL\nPredict ['=', 'a', 'b', 'c', 'd']\n(10)\t LPAREN -> (\nPredict ['(']\n(11)\t MINUS -> -\nPredict ['-']\n(12)\t PLUS -> +\nPredict ['+']\n(13)\t QUANTIFIER -> GROUPING\nPredict ['(', '=', 'a', 'b', 'c', 'd']\n(14)\t QUANTIFIER -> GROUPING PLUS\nPredict ['(', '=', 'a', 'b', 'c', 'd']\n(15)\t QUANTIFIER -> GROUPING STAR\nPredict ['(', '=', 'a', 'b', 'c', 'd']\n(16)\t RPAREN -> )\nPredict [')']\n(17)\t SEQUENCE -> QUANTIFIER\nPredict ['(', '=', 'a', 'b', 'c', 'd']\n(18)\t SEQUENCE -> QUANTIFIER SEQUENCE\nPredict ['(', '=', 'a', 'b', 'c', 'd']\n(19)\t STAR -> *\nPredict ['*']\n(20)\t TERMINAL -> = CHAR MINUS CHAR\nPredict ['=']\n(21)\t TERMINAL -> CHAR\nPredict ['a', 'b', 'c', 'd']\n(22)\t TERMINAL -> RANGE\nPredict []\n(23)\t \ufeffREGEX -> ALTERNATION $\nPredict ['(', '=', 'a', 'b', 'c', 'd']\n(24)\t \ufeffREGEX -> lambda $\nPredict ['$']\nGrammar Start Symbol or Goal: \ufeffREGEX\n\nFirst sets:\nALTERNATION : []\nBAR : []\nCHAR : []\nGROUPING : []\nLPAREN : []\nMINUS : []\nPLUS : []\nQUANTIFIER : []\nRANGE : []\nRPAREN : []\nSEQUENCE : []\nSTAR : []\nTERMINAL : []\n\ufeffREGEX : []\nFollow sets:\nALTERNATION : ['$', ')']\nBAR : ['(', '=', 'a', 'b', 'c', 'd']\nCHAR : ['$', '(', ')', '*', '+', '-', '=', 'a', 'b', 'c', 'd', '“|”']\nGROUPING : ['$', '(', ')', '*', '+', '=', 'a', 'b', 'c', 'd', '“|”']\nLPAREN : ['(', '=', 'a', 'b', 'c', 'd']\nMINUS : ['a', 'b', 'c', 'd']\nPLUS : ['$', '(', ')', '=', 'a', 'b', 'c', 'd', '“|”']\nQUANTIFIER : ['$', '(', ')', '=', 'a', 'b', 'c', 'd', '“|”']\nRANGE : ['$', '(', ')', '*', '+', '=', 'a', 'b', 'c', 'd', '“|”']\nRPAREN : ['$', '(', ')', '*', '+', '=', 'a', 'b', 'c', 'd', '“|”']\nSEQUENCE : ['$', ')', '“|”']\nSTAR : ['$', '(', ')', '=', 'a', 'b', 'c', 'd', '“|”']\nTERMINAL : ['$', '(', ')', '*', '+', '=', 'a', 'b', 'c', 'd', '“|”']\n\ufeffREGEX : []\n")
